# database container
mariadb:
  image: mariadb
  environment:
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    - "MYSQL_USER=${MYSQL_USER}"
    - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
  labels:
    io.rancher.scheduler.affinity:host_label: host.type=data
  volumes:
    - "/home/data/${PATH}/mysql:/var/lib/mysql"
  log_opt:
    gelf-address: "udp://logstash:12201"
    tag: "php"

# php container
php:
  image: vidavenel/php:presta
  volumes:
    - "/home/data/${PATH}/public_html/:/var/www/html"
  labels:
    io.rancher.scheduler.affinity:host_label: host.type=compute
  mem_limit: 2097152000
  memswap_limit: 2097152000
  log_opt:
    gelf-address: "udp://logstash:12201"
    tag: "php"

# nginx container
nginx:
  image: nginx
  volumes:
    - "/home/data/${PATH}/public_html/:/var/www/html"
    - "/home/data/${PATH}/nginx/conf.d:/etc/nginx/conf.d"
  labels:
    io.rancher.scheduler.affinity:host_label: host.type=compute
#  log_driver: gelf
  log_opt:
    gelf-address: "udp://logstash:12201"
    tag: "nginx"
  mem_limit: 2097152000
  memswap_limit: 2097152000

# logstash container
logstash:
  image: logstash
  volumes:
    - "/home/data/${PATH}/logstash:/conf"
  command: logstash -f /conf/gelf.conf --verbose
  environment:
    - "TZ=Europe/Paris"
  labels:
    io.rancher.scheduler.affinity:host_label: host.type=data
