# database container
mariadb:
  image: mariadb
  environment:
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    - "MYSQL_USER=${MYSQL_USER}"
    - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
  labels:
    io.rancher.scheduler.affinity:host_label: host.type=data

web:
  image: vidavenel/prestashop
  labels:
    io.rancher.scheduler.affinity:host_label: host.type=compute
