# image apache + mod php
web:
  image: prestashop/prestashop:1.6

# database container
mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE:${MYSQL_DATABASE}
    - MYSQL_USER:${MYSQL_USER}
    - MYSQL_PASSWORD:${MYSQL_PASSWORD}