.catalog:
  name: Prestashop
  version: 0.2
  description: stack Prestashop (déprécié pas de persistence des données 2 services mariadb et php:apache)
  uuid: prestashop-0
  questions:
    - variable: MYSQL_ROOT_PASSWORD
      label: MYSQL_ROOT_PASSWORD
      description: | # mot de passe root de la base de données.
      default: root
      type: "string"
    - variable: MYSQL_DATABASE
      label: MYSQL_DATABASE
      description: | # nom de la base de données.
      default: prestashop
      type: "string"
    - variable: MYSQL_USER
      label: MYSQL_USER
      description: | # utilisateur de la base de données.
      default: prestashop
      type: "string"
    - variable: MYSQL_PASSWORD
      label: MYSQL_PASSWORD
      description: | # mot de passe de la base de données.
      default: prestashop
      type: "string"