name: prestashop
description: |
  # Description of the Catalog Entry stack prestashop
version: 0.1
category: CMS
maintainer: Vincent DAVENEL <vincent@aiglecom.com>
#license: # The license
#projectURL: # A URL related to the catalog entry
